### ISSUE TITLE
Help: Terminal window is too small 80×12

### ISSUE THREAD

**Issue by sunmughan** [grm34/ZenMaxBuilder#719]
Terminal window is too small, how to fix this?
![Screenshot_20220730-120922_Termux](https://user-images.githubusercontent.com/18499082/181878213-7f239db1-673e-40a0-94ff-e977da288f24.png)

**Comment by grm34** [comment]
Hello.

The default size of the Termux window is too big to display menuconfig.

Simply reduce the size of the Termux window by at least one notch with your two fingers.

I can increase the minimum size accepted by ZMB in order to use it with the default Termux window size but an error will occur each time launching menuconfig.

PS: included toolchains are built on x86_64 and will not work on Termux (see https://github.com/grm34/ZenMaxBuilder#toolchains)
